language: ruby
cache: bundler
before_install:
  - gem install bundler -v '>= 1.5.1'
bundler_args: --without development
rvm:
  - 2.0.0
  - 2.1.0
before_script:
  - bundle exec rake app:db:create
  - bundle exec rake app:db:test:load
script:
  - "cd spec/dummy && bundle exec rspec spec"
services:
  - elasticsearch